### ISSUE TITLE
react-testing-library changed import

### ISSUE THREAD

**Issue by felipediogo** [hyanmandian/react-etalpreliob#17]
https://github.com/testing-library/react-testing-library

It changed from `react-testing-library` to `@testing-library/react`

and it gives a warning when you install using the old name.

**Comment by felipediogo** [comment]
https://github.com/hyanmandian/react-etalpreliob/pull/18

The pullrequest fixing it

**Comment by felipediogo** [comment]
![image](https://user-images.githubusercontent.com/26486135/58965747-77196b00-8787-11e9-9c91-9572d2aa28c9.png)
The image o the warning

**Comment by felipediogo** [comment]
Also as a **suggestion** when you commit to this repository makes sure you change the [package-lock.json](https://github.com/hyanmandian/react-etalpreliob/blob/14cc25760d44b490d1afad351386bddd9cafe206/package-lock.json#L9), otherwise you could possibly give information about your employeer.

**Comment by hyanmandian** [comment]
closed by #18
